apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - cloudflare-externalsecret.yaml  # Temporarily disabled - using manual secret
  - cluster-issuer-staging.yaml
  - cluster-issuer.yaml
  - wildcard-certificate.yaml
