apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  labels:
    app.kubernetes.io/name: onepassword-connect
    app.kubernetes.io/component: secretstore
    app.kubernetes.io/managed-by: flux
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        civilsnut.se: 1 # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
