apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph
  annotations:
    flux.weave.works/depends-on: "cert-manager"
resources:
  - namespace.yaml
  - repository.yaml
  - operator-release.yaml
  - cluster-release.yaml
  - httproute.yaml
  - referencegrant.yaml
  - vmservicescrape.yaml
