apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    # Depends on cert-manager for TLS certificates
    flux.weave.works/depends-on: "cert-manager"

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - httproute.yaml
  - referencegrant.yaml
