apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - configmap-headers.yaml
  - configmap-mqtt.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
