apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - flux-podmonitor.yaml
  - flux-servicemonitor.yaml

configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml

generatorOptions:
  disableNameSuffixHash: true
