apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    # Depends on external-secrets for secrets, rook-ceph for storage, shared-gateway for ingress
    flux.weave.works/depends-on: "external-secrets,rook-ceph,shared-gateway"

resources:
  - namespace.yaml
  - manifests
  - httproute.yaml
  - referencegrant.yaml
  - service-coap-lb.yaml
