apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: unifi-bgp-policy
  namespace: kube-system
spec:
  virtualRouters:
  - exportPodCIDR: false
    localASN: 65512
    neighbors:
    - connectRetryTimeSeconds: 120
      eBGPMultihopTTL: 1
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      peerASN: 65510
      peerAddress: 192.168.1.1/32
      peerPort: 179
    serviceSelector:
      matchExpressions:
      - {key: somekey, operator: NotIn, values: ['never-used-value']}
