apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ipv4-pool"
spec:
  blocks:
    - start: "192.168.4.10"
      stop: "192.168.4.250"
    - start: "192.168.1.150"
      stop: "192.168.1.159"
  serviceSelector:
    matchExpressions:
      - { key: io.cilium/lb-pool, operator: NotIn, values: [iot] }
