apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: "iot-ipv4-pool"
spec:
  disabled: false
  blocks:
    - start: "192.168.3.200"
      stop: "192.168.3.250"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: iot
