apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    # Depends on cilium for Gateway API CRDs
    flux.weave.works/depends-on: "cilium"

resources:
  - namespace.yaml
  - gateway.yaml
  - rbac.yaml
  - referencegrant.yaml
