apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium-agent-servicemonitor.yaml
  - cilium-gateway-prometheusrule.yaml
  - cilium-gateway-recordingrules.yaml
  - cilium-operator-servicemonitor.yaml
  - gateway-api-crs-config.yaml
  - gateway-api-servicemonitor.yaml
  - httproute-dashboard.yaml
  - hubble-relay-servicemonitor.yaml
