apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    # Depends on external-secrets for secrets, longhorn for storage, shared-gateway for ingress
    flux.weave.works/depends-on: "external-secrets,longhorn,shared-gateway"

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - httproute.yaml
  - referencegrant.yaml
