apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - mqtt-credentials-externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - mqtt-loadbalancer.yaml
  - httproute.yaml
  - referencegrant.yaml
  - vmservicescrape.yaml
