apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mqtt-credentials
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mqtt-credentials
    app.kubernetes.io/component: externalsecret
    app.kubernetes.io/managed-by: flux
    app: mosquitto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mqtt-credentials-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: mosquitto
  refreshInterval: 1h
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "MQTT Credentials"
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "MQTT Credentials"
        property: password
    - secretKey: password-file
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "MQTT Credentials"
        property: password-file
